import React from 'react';
import Circle from './Circle';

const CaptivatingLight = () => {
  


  return (
    <div className="bg-zinc-800 w-full h-full justify-center items-center flex">
      <div className="[font-family:'Josefin_Sans-Bold',Helvetica] font-bold text-[#3e3e3e] text-[96px] tracking-[0] leading-[normal] whitespace-nowrap">
          DESMOND FOO
      </div>
      <div className={`flex flex-wrap w-[750px] gap-[0px_0px] absolute`}>
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
          <Circle />
      </div>
    </div>
  )
}

export default CaptivatingLight;